//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef.pricebuilder.net.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.WorkItems = new HashSet<WorkItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public System.DateTime CreateTS { get; set; }
        public string CreateUID { get; set; }
        public Nullable<System.DateTime> UpdateTS { get; set; }
        public string UPDATEUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItem> WorkItems { get; set; }
    }
}
