//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef.pricebuilder.net.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
        public Nullable<short> SortOrder { get; set; }
        public System.DateTime CreateTS { get; set; }
        public string CreateUID { get; set; }
        public Nullable<System.DateTime> UpdateTS { get; set; }
        public string UpdateUID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
